apiVersion: v1
kind: PersistentVolume
metadata:
  name: foodapppv
  labels:
    name: foodapppv
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-db
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"